### PR TITLE
13 - List available workshops on homepage

### PR DESCRIPTION
**Pull request by leovujanic**
Added workshops listing on homepage.

Closes: #13

### CODE REVIEW

**Comment by leovujanic** [comment]
I think we need db access for CircleCi to work.
And I need to change or delete `HomepageControllerTest::testHomepage()`. @msvrtan any suggestions? I have no idea how to test new home page version.

**Comment by msvrtan** [comment]
Credentials for tests are located in phpunit.xml.dist, and they are generic ones so thats the issue .. they should be bob/n0p455

**Comment by leovujanic** [comment]
@msvrtan now config is OK. But my test is invalid, because it is old test for old homepage (It was JSON output). Do I need test for new homepage? I don't know how that test should look like. Can you give me a hint?

**Comment by msvrtan** [comment]
Of course, as you changed homepage :)

I would modify the assert to check for the existance of 'Currently, there are no active workshops.' (ATM)

**Pull request merged**
