### PR TITLE
Sensitive data leakage detected

### PR DESCRIPTION
**Pull request by leovujanic**
Removed mysql user data form env.dist file.

### CODE REVIEW

**Comment by msvrtan** [comment]
No worries, those are only local dev credentials :)

They are in the dist file so each new developer (or maybe if you switch laptops) can easily generate .env file from and start working without trying to figure out details of the local setup. (as you can see .env file is ignored so whenever you want to change something locally for your setup it will not be commited to repo)

**Comment by leovujanic** [comment]
Yes I know, this was kind of little mental training. Fix it once, and remember forever not to write passwords in .dist file. :)

Maybe off of topic, but question is related to .env file. Let's say I am using Deployer (last PHP meetup) and I have 4 folders that are symlinked to public dir. In the beginning, directories don't exist and once repo is pulled into dir .env file needs to be created. Doing it manually after each build doesn't sound right, so, how to handle that? In production keep .env file outside project structure or?

**Comment by leovujanic** [comment]
Was this intentionally to remember credentials for the vagrant box?

**Comment by msvrtan** [comment]
Yeah, but passwords in dist should not be production ones :)

I dont have too much experience with .env as this is the new thing, what I understood idea is to use .env file outside of the production and on production have env variables set via either web server of php-fpm (I do use .env file in prod as well as I'm getting used to this changes and I do keep it outside so I copy it when deploying )

**Pull request merged**
